version: '3.5'

services:
  website:
    build:
      context: '.'
    container_name: website-app
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
    depends_on:
      - "website-db"
      - "website-mail"
      - "website-nodejs" 
      - "website-redis"
    networks:
      - app

  website-db:
    image: mysql:8
    tty: true
    container_name: website-db
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - DB_CONNECTION=mysql
      - DB_HOST=website-db
      - DB_PORT=3306
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      - app

  website-mail:
    image: mailhog/mailhog:latest
    container_name: website-mail
    ports:
      - "8125:8025"
      - "2525:1025"
    environment:
      - MT_USER=dashfluit
      - MT_PASSWD=dashfluit
      - MT_MAILBOX_LIMIT=512000001
      - MT_MESSAGE_LIMIT=102400001'
    networks:
      - app
    
  website-redis:
    image: redis:latest
    container_name: website-redis
    ports:
      - 6379:6379
    networks:
      - app

  website-nodejs:  # Adicionando o serviço Node.js
    image: node:latest  # Use a versão do Node.js desejada
    container_name: website-nodejs
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html/
    command: ["npm", "run", "dev"]  # Substitua pelo seu comando Vite
    ports:
      - 3009:3009
    depends_on:
      - "website-db"
    networks:
      - app

networks:
  app:
    driver: bridge
