name: Trigger auto deployment for laravel-vite

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/laravel-vite-AutoDeployTrigger-c36f6ed6-2188-486e-bb4b-f2199e93774e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.LARAVELVITE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LARAVELVITE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LARAVELVITE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.LARAVELVITE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LARAVELVITE_REGISTRY_PASSWORD }}
          containerAppName: laravel-vite
          resourceGroup: laravel-vite
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


